# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 'Angular PR Build'
trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.6.x'
  displayName: 'Install Node.js'

- script: |
    cd AngularApp
    npm install -g npm@8.19.2
    npm install -g @angular/cli@11.1.2
    npm install
    npm run build
  displayName: 'npm install and build'
